name: Build

on:
  push:
    paths-ignore:
      - '**.md'

permissions:
  checks: write

jobs:
  run-build:
    name: Run clippy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup show active-toolchain

      - name: Build
        run: cargo build
