name: Build

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.*'

  pull_request:
    branches:
      - master

permissions:
  checks: write

jobs:
  run-build:
    name: Run cargo build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Install toolchain
        run: rustup show active-toolchain

      - name: Build
        run: cargo build
