name: QA

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.*'

permissions:
  checks: write

jobs:
  check-qa:
    name: Run clippy & formatter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Install toolchain
        run: rustup show active-toolchain

      - name: Check linting
        run: cargo clippy

      - name: Check formatting
        run: cargo fmt --check

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Install toolchain
        run: rustup show active-toolchain

      - name: Run tests
        run: cargo test
