name: Lint

on:
  push:
    paths-ignore:
      - Dockerfile
      - '**.md'

permissions:
  checks: write

jobs:
  run-backend-linter:
    name: Run clippy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup show active-toolchain

      - name: Build app
        run: cargo clippy